import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[shell]
program = "/bin/tmux"
args = ["-l"]
[font]
normal = { family = "JetBrainsMono NF", style = "normal" }
size = 10.5
[window]    
dynamic_padding = true
opacity = 0.95
